### ISSUE TITLE
Got all the way to the end and then this

### ISSUE THREAD

**Issue by paperc07** [jordon31/OF-SCR#18]
An error has occurred: [WinError 5] Access is denied: 'profiles'
Traceback (most recent call last):
  File "C:\Users\paper\Desktop\OF-SCR-main\of-scr.py", line 540, in <module>
    assure_dir("profiles")
  File "C:\Users\paper\Desktop\OF-SCR-main\of-scr.py", line 76, in assure_dir
    os.makedirs(path, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'profiles'

Please try again.

Enter the profile name to download (use TAB for to see the full list):

**Comment by paperc07** [comment]
nvm had to be ran as admin
